
DATABASE:
    host :
    db     :
    user   :
    pwd    :

GENERAL:
    koa_base_path :
    max_errors: 10
    max_lock_retries: 20 # cycles
    lock_chk_period: 60 # seconds
    log_dir: .

FDT_PKG:
    pkg_timeout: 60 # minutes
    monitor_period: 5 # seconds

FDT_XFR:
    xfr_timeout: 120 # minutes
    monitor_period: 5 # seconds

SCALES:
    # 250 GB = 256000 MB
    max_pkg_size : 256000 # MB
    inst_prefixes: [SS, SI]

